# Generated by Django 2.2.4 on 2019-08-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=255, verbose_name='Gênero')),
                ('interesse', models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End'), ('Mobile', 'Mobile'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science')], max_length=255, verbose_name='Interesse')),
                ('telefone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('senha', models.CharField(max_length=25, verbose_name='Senha')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inst', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('segmento', models.CharField(choices=[('Educacional', 'Organização não governamental educacional'), ('Ambiental', 'Organização não governamental ambiental'), ('Médica', 'Organização não governamental médica')], max_length=255, verbose_name='Segmento da Instituição')),
                ('telefone_inst', models.CharField(max_length=30, verbose_name='Telefone da Instituiçao')),
                ('email_inst', models.EmailField(max_length=255, verbose_name='Email da Instituição')),
                ('senha_inst', models.CharField(max_length=25, verbose_name='Senha')),
                ('data_criacao_inst', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255, verbose_name='Nome do projeto')),
                ('descricao', models.TextField(verbose_name='Descreva seu projeto')),
                ('proposta', models.TextField(verbose_name='Faça uma proposta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(on_delete=None, to='website.Instituicao')),
            ],
        ),
    ]
